### ISSUE TITLE
Decide a tracking solution

### ISSUE THREAD

**Issue by alidursen** [swe-ms-boun/2018fall-swe574-g1#2]
Is Github projects page enough? How will we track who's assigned to what?

**Comment by alidursen** [comment]
sure, but is "review" a "to do" task or "in progress"? i mean, if we're to simplify, _review_ can just be a tag for issues

**Comment by vedatakses** [comment]
Yes, review tag would also appropriate, just we need to make sure people about some of the items are waiting for reviews.

Let's tag them as review once we complete working on it and assign to proper people, and if we want to see them in issue tracking system, then we may consider creating section for it as well.

**Comment by tugcanolgun** [comment]
I agree with @vedatakses in a way that we shouldn't have In-relaxed-progress or in-urgent-progress. Their appropriate issue tags for low priority and high priority should separate them and we should have one Work in progress part. When it comes to Review, I cannot comment on that since I have never seen it used anywhere nor have I heard about it. If it is useful, we can use it. I am neutral about Review.

**Comment by alidursen** [comment]
are we done with tracking? is the issue satisfied, or should we reach a conclusion?
